version: '3'

# this is local dev file, prod need modifications

services:
  backend:
    container_name: backend
    build: ./be
    restart: always
    volumes:
      - './:/app'
      - '/db.sqlite3'
    ports:
      - 8000:8000
    env_file:
      - ./be/dev-variables.env
    entrypoint: ./dev-entrypoint.sh