# Generated by Django 5.0.1 on 2024-01-23 14:39

import django.core.validators
import django.db.models.deletion
import reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expire', models.DateTimeField(default=reservation.models.calc_expiration_date)),
                ('card_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='card.carditem')),
            ],
        ),
    ]
