# Generated by Django 5.0.1 on 2024-01-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
